enum CombatStyle { blades, greatsword, magic }

enum ContractRarity { common, elite, heroic, legendary }

enum MercenaryDuty { combat, support, dispatch }

enum UltimatePattern {
  lunarFlurry,
  bloodMoonRampage,
  foxfireIllusion,
  meteorPursuit,
  goldenSanctuary,
  skyTactics,
  earthPiercer,
  twinMoonSigil,
}

enum WeaponPattern {
  twinSlash,
  bloodCleave,
  chainFlame,
  swordStrike,
  longBow,
  emberBurst,
  spearLine,
  shadowPierce,
  rapidVolley,
  shieldOrbit,
  runeMine,
  featherChain,
  halberdSweep,
  crescentWave,
  frostTotem,
  spiritFamiliar,
}

class MercenarySpec {
  const MercenarySpec({
    required this.id,
    required this.name,
    required this.epithet,
    required this.race,
    required this.job,
    required this.trait,
    required this.traitDescription,
    required this.level,
    required this.power,
    required this.maxHp,
    required this.speed,
    required this.attackInterval,
    required this.baseDamage,
    required this.style,
    required this.signatureWeaponId,
    required this.ultimate,
    required this.ultimatePattern,
    this.rarity = ContractRarity.legendary,
    this.duty = MercenaryDuty.combat,
    this.supportEffect = '',
  });

  final String id;
  final String name;
  final String epithet;
  final String race;
  final String job;
  final String trait;
  final String traitDescription;
  final int level;
  final int power;
  final int maxHp;
  final double speed;
  final double attackInterval;
  final int baseDamage;
  final CombatStyle style;
  final String signatureWeaponId;
  final String ultimate;
  final UltimatePattern ultimatePattern;
  final ContractRarity rarity;
  final MercenaryDuty duty;
  final String supportEffect;

  bool get canDeploy => duty == MercenaryDuty.combat;
}

class WeaponSpec {
  const WeaponSpec({
    required this.id,
    required this.name,
    required this.grade,
    required this.attack,
    required this.crit,
    required this.speed,
    required this.description,
    required this.pattern,
    this.ownerId,
  });

  final String id;
  final String name;
  final String grade;
  final int attack;
  final int crit;
  final int speed;
  final String description;
  final WeaponPattern pattern;
  final String? ownerId;
}

const alphaMercenaries = <MercenarySpec>[
  MercenarySpec(
    id: 'luna',
    name: '루나 벨하르트',
    epithet: '달빛의 그림자',
    race: '묘족',
    job: '암살자',
    trait: '야행성',
    traitDescription: '어두운 전장에서 공격속도 20%, 치명타 확률 15% 증가',
    level: 45,
    power: 28450,
    maxHp: 1320,
    speed: 160,
    attackInterval: .42,
    baseDamage: 2,
    style: CombatStyle.blades,
    signatureWeaponId: 'moon_blades',
    ultimate: '월식 · 백야난무',
    ultimatePattern: UltimatePattern.lunarFlurry,
  ),
  MercenarySpec(
    id: 'kael',
    name: '카일 로젠팽',
    epithet: '피 묻은 선봉',
    race: '늑대족',
    job: '검투사',
    trait: '사냥의 고양',
    traitDescription: '연속 처치마다 공격력이 상승하며 체력이 소량 회복',
    level: 42,
    power: 26920,
    maxHp: 1680,
    speed: 135,
    attackInterval: .62,
    baseDamage: 3,
    style: CombatStyle.greatsword,
    signatureWeaponId: 'blood_fang',
    ultimate: '혈월 · 야수해방',
    ultimatePattern: UltimatePattern.bloodMoonRampage,
  ),
  MercenarySpec(
    id: 'sera',
    name: '세라 이나리온',
    epithet: '유리불꽃 술사',
    race: '여우족',
    job: '환술사',
    trait: '여우불 장막',
    traitDescription: '상태이상에 걸린 적에게 마법 피해 25% 증가',
    level: 40,
    power: 25840,
    maxHp: 1110,
    speed: 145,
    attackInterval: .55,
    baseDamage: 2,
    style: CombatStyle.magic,
    signatureWeaponId: 'glass_flame',
    ultimate: '천화 · 몽환구미진',
    ultimatePattern: UltimatePattern.foxfireIllusion,
  ),
  MercenarySpec(
    id: 'nyra',
    name: '니라 베일',
    epithet: '바람보다 빠른 귀',
    race: '토끼족',
    job: '척후병',
    trait: '선행 사격',
    traitDescription: '먼 적을 공격할수록 피해와 이동속도가 증가',
    level: 38,
    power: 24780,
    maxHp: 1080,
    speed: 172,
    attackInterval: .38,
    baseDamage: 2,
    style: CombatStyle.blades,
    signatureWeaponId: 'gale_string',
    ultimate: '천궁 · 유성추적진',
    ultimatePattern: UltimatePattern.meteorPursuit,
    rarity: ContractRarity.heroic,
  ),
  MercenarySpec(
    id: 'aurel',
    name: '아우렐 하르트',
    epithet: '백각의 성벽',
    race: '사슴족',
    job: '성기사',
    trait: '수호의 뿔',
    traitDescription: '목표물 가까이에서 최대 체력과 반격 피해 증가',
    level: 41,
    power: 27310,
    maxHp: 1920,
    speed: 122,
    attackInterval: .68,
    baseDamage: 3,
    style: CombatStyle.greatsword,
    signatureWeaponId: 'sunwall_aegis',
    ultimate: '성역 · 황금녹각성',
    ultimatePattern: UltimatePattern.goldenSanctuary,
  ),
  MercenarySpec(
    id: 'vesta',
    name: '베스타 코르벤',
    epithet: '적갈빛 전술익',
    race: '조류계',
    job: '전술사',
    trait: '전황 독해',
    traitDescription: '전장 사건 이후 스킬 재사용과 연쇄 범위 증가',
    level: 39,
    power: 25560,
    maxHp: 1160,
    speed: 148,
    attackInterval: .52,
    baseDamage: 2,
    style: CombatStyle.magic,
    signatureWeaponId: 'corvus_codex',
    ultimate: '전개 · 천공전술도',
    ultimatePattern: UltimatePattern.skyTactics,
    rarity: ContractRarity.heroic,
  ),
  MercenarySpec(
    id: 'rask',
    name: '라스크 드라벤',
    epithet: '청동비늘 파쇄창',
    race: '파충류계',
    job: '창병',
    trait: '냉혈 집중',
    traitDescription: '이동을 멈추면 관통력과 공격 범위가 점차 증가',
    level: 43,
    power: 27940,
    maxHp: 1580,
    speed: 132,
    attackInterval: .58,
    baseDamage: 3,
    style: CombatStyle.greatsword,
    signatureWeaponId: 'verdigris_halberd',
    ultimate: '역린 · 지맥관통창',
    ultimatePattern: UltimatePattern.earthPiercer,
    rarity: ContractRarity.heroic,
  ),
  MercenarySpec(
    id: 'iris',
    name: '아이리스 녹티스',
    epithet: '성흔의 마검',
    race: '환수계',
    job: '마검사',
    trait: '성흔 공명',
    traitDescription: '마법과 근접 공격을 번갈아 사용하면 치명타 피해 증가',
    level: 44,
    power: 28610,
    maxHp: 1380,
    speed: 151,
    attackInterval: .46,
    baseDamage: 3,
    style: CombatStyle.magic,
    signatureWeaponId: 'noctis_crescent',
    ultimate: '환성 · 쌍월성흔검',
    ultimatePattern: UltimatePattern.twinMoonSigil,
    rarity: ContractRarity.heroic,
  ),
  MercenarySpec(
    id: 'mira',
    name: '미라 펠린',
    epithet: '등불 든 의무병',
    race: '묘족',
    job: '의무병',
    trait: '야전 처치',
    traitDescription: '전투 후 부상 손실을 줄이고 패배 보존율을 높인다.',
    level: 24,
    power: 15100,
    maxHp: 1120,
    speed: 142,
    attackInterval: .58,
    baseDamage: 2,
    style: CombatStyle.magic,
    signatureWeaponId: 'spirit_lantern',
    ultimate: '응급 전선',
    ultimatePattern: UltimatePattern.foxfireIllusion,
    rarity: ContractRarity.common,
    duty: MercenaryDuty.support,
    supportEffect: '패배 보상 보존 +10% · 회복품 획득 +1',
  ),
  MercenarySpec(
    id: 'garr',
    name: '가르 브란트',
    epithet: '닳은 방패',
    race: '늑대족',
    job: '방패병',
    trait: '전열 교대',
    traitDescription: '두꺼운 방패와 교대 엄호로 출전 용병의 생존력을 보강한다.',
    level: 28,
    power: 18400,
    maxHp: 1880,
    speed: 116,
    attackInterval: .72,
    baseDamage: 3,
    style: CombatStyle.greatsword,
    signatureWeaponId: 'sunwall_aegis',
    ultimate: '노병의 방벽',
    ultimatePattern: UltimatePattern.goldenSanctuary,
    rarity: ContractRarity.elite,
    duty: MercenaryDuty.support,
    supportEffect: '출전 용병 최대 체력 +12%',
  ),
  MercenarySpec(
    id: 'talia',
    name: '탈리아 로웬',
    epithet: '붉은 장부',
    race: '여우족',
    job: '보급척후',
    trait: '전리품 감정',
    traitDescription: '파견과 보급 계약에서 추가 골드와 재료를 확보한다.',
    level: 25,
    power: 16200,
    maxHp: 1050,
    speed: 168,
    attackInterval: .44,
    baseDamage: 2,
    style: CombatStyle.blades,
    signatureWeaponId: 'war_bow',
    ultimate: '붉은 항로',
    ultimatePattern: UltimatePattern.meteorPursuit,
    rarity: ContractRarity.common,
    duty: MercenaryDuty.dispatch,
    supportEffect: '파견 골드 +18% · 보급 재료 +1',
  ),
  MercenarySpec(
    id: 'fenn',
    name: '펜 러너',
    epithet: '밤길 전령',
    race: '토끼족',
    job: '전령',
    trait: '급행 계약',
    traitDescription: '파견 시간을 단축하고 전장 사건 대응력을 높인다.',
    level: 23,
    power: 14900,
    maxHp: 980,
    speed: 180,
    attackInterval: .40,
    baseDamage: 2,
    style: CombatStyle.blades,
    signatureWeaponId: 'guard_spear',
    ultimate: '질풍 전달',
    ultimatePattern: UltimatePattern.earthPiercer,
    rarity: ContractRarity.common,
    duty: MercenaryDuty.dispatch,
    supportEffect: '파견 완료 요구 전투 -1 · 사건 경험치 +8%',
  ),
  MercenarySpec(
    id: 'elka',
    name: '엘카 하르덴',
    epithet: '성벽의 공병',
    race: '사슴족',
    job: '공병',
    trait: '공성 해체',
    traitDescription: '공성 병기와 지휘관을 상대할 때 전술 보상을 높인다.',
    level: 30,
    power: 19800,
    maxHp: 1520,
    speed: 124,
    attackInterval: .66,
    baseDamage: 3,
    style: CombatStyle.greatsword,
    signatureWeaponId: 'iron_sword',
    ultimate: '성벽 역설계',
    ultimatePattern: UltimatePattern.skyTactics,
    rarity: ContractRarity.elite,
    duty: MercenaryDuty.support,
    supportEffect: '공성 적 피해 +10% · 고철 획득 +1',
  ),
  MercenarySpec(
    id: 'soren',
    name: '소렌 바스크',
    epithet: '검은숲 길잡이',
    race: '파충류계',
    job: '추적자',
    trait: '안개길',
    traitDescription: '기습과 암살 계약에서 적 증원 속도를 늦춘다.',
    level: 27,
    power: 17600,
    maxHp: 1300,
    speed: 154,
    attackInterval: .50,
    baseDamage: 2,
    style: CombatStyle.blades,
    signatureWeaponId: 'gale_string',
    ultimate: '무흔 추적',
    ultimatePattern: UltimatePattern.meteorPursuit,
    rarity: ContractRarity.elite,
    duty: MercenaryDuty.support,
    supportEffect: '기습·암살 계약 공격력 +10%',
  ),
  MercenarySpec(
    id: 'corva',
    name: '코르바 네스트',
    epithet: '검은 편지',
    race: '조류계',
    job: '정보장교',
    trait: '전황 보고',
    traitDescription: '세력 평판과 작전 진행 보상을 증폭한다.',
    level: 31,
    power: 20500,
    maxHp: 1100,
    speed: 150,
    attackInterval: .52,
    baseDamage: 2,
    style: CombatStyle.magic,
    signatureWeaponId: 'corvus_codex',
    ultimate: '흑익 전문',
    ultimatePattern: UltimatePattern.skyTactics,
    rarity: ContractRarity.elite,
    duty: MercenaryDuty.dispatch,
    supportEffect: '세력 평판 +2 · 파견 작전 경험 +20%',
  ),
  MercenarySpec(
    id: 'silas',
    name: '실라스 베른',
    epithet: '청록 보급관',
    race: '여우족',
    job: '보급술사',
    trait: '전시 조달',
    traitDescription: '훈련과 대장간 소모 비용을 효율적으로 관리한다.',
    level: 29,
    power: 19100,
    maxHp: 1180,
    speed: 138,
    attackInterval: .56,
    baseDamage: 2,
    style: CombatStyle.magic,
    signatureWeaponId: 'frost_standard',
    ultimate: '청록 보급진',
    ultimatePattern: UltimatePattern.foxfireIllusion,
    rarity: ContractRarity.elite,
    duty: MercenaryDuty.dispatch,
    supportEffect: '훈련 골드 -10% · 파견 강화 재료 +1',
  ),
];

String contractRarityName(ContractRarity rarity) => switch (rarity) {
  ContractRarity.common => '일반',
  ContractRarity.elite => '정예',
  ContractRarity.heroic => '영웅',
  ContractRarity.legendary => '전설',
};

String mercenaryDutyName(MercenaryDuty duty) => switch (duty) {
  MercenaryDuty.combat => '출전',
  MercenaryDuty.support => '지원',
  MercenaryDuty.dispatch => '파견',
};

const alphaWeapons = <WeaponSpec>[
  WeaponSpec(
    id: 'moon_blades',
    name: '월광쌍검',
    grade: '전설',
    attack: 1285,
    crit: 18,
    speed: 14,
    description: '치명타 발생 시 40% 확률로 추가 참격',
    pattern: WeaponPattern.twinSlash,
    ownerId: 'luna',
  ),
  WeaponSpec(
    id: 'blood_fang',
    name: '혈아대검',
    grade: '전설',
    attack: 1510,
    crit: 9,
    speed: -5,
    description: '연속 처치 시 공격 범위와 흡혈량 증가',
    pattern: WeaponPattern.bloodCleave,
    ownerId: 'kael',
  ),
  WeaponSpec(
    id: 'glass_flame',
    name: '유리불꽃 지팡이',
    grade: '전설',
    attack: 1190,
    crit: 13,
    speed: 8,
    description: '투사체가 적 사이를 두 번 도약',
    pattern: WeaponPattern.chainFlame,
    ownerId: 'sera',
  ),
  WeaponSpec(
    id: 'iron_sword',
    name: '용병단 철검',
    grade: '희귀',
    attack: 720,
    crit: 5,
    speed: 3,
    description: '정직하고 안정적인 전장용 장검',
    pattern: WeaponPattern.swordStrike,
  ),
  WeaponSpec(
    id: 'war_bow',
    name: '철각 전궁',
    grade: '희귀',
    attack: 650,
    crit: 12,
    speed: 6,
    description: '먼 거리 적을 우선 공격',
    pattern: WeaponPattern.longBow,
  ),
  WeaponSpec(
    id: 'ember_orb',
    name: '잔불 보주',
    grade: '영웅',
    attack: 880,
    crit: 8,
    speed: 10,
    description: '일정 확률로 작은 폭발 발생',
    pattern: WeaponPattern.emberBurst,
  ),
  WeaponSpec(
    id: 'guard_spear',
    name: '수문장 장창',
    grade: '희귀',
    attack: 790,
    crit: 4,
    speed: 0,
    description: '공격 범위가 크게 증가',
    pattern: WeaponPattern.spearLine,
  ),
  WeaponSpec(
    id: 'shadow_knife',
    name: '그림자 투척검',
    grade: '영웅',
    attack: 830,
    crit: 16,
    speed: 12,
    description: '낮은 확률로 관통 투척검 발사',
    pattern: WeaponPattern.shadowPierce,
  ),
  WeaponSpec(
    id: 'gale_string',
    name: '질풍시위',
    grade: '전설',
    attack: 1120,
    crit: 19,
    speed: 18,
    description: '세 방향 속사 후 가장 먼 적을 추적',
    pattern: WeaponPattern.rapidVolley,
    ownerId: 'nyra',
  ),
  WeaponSpec(
    id: 'sunwall_aegis',
    name: '태양벽 성순',
    grade: '전설',
    attack: 1420,
    crit: 6,
    speed: -8,
    description: '주위를 선회하며 목표물 근처 적을 밀어냄',
    pattern: WeaponPattern.shieldOrbit,
    ownerId: 'aurel',
  ),
  WeaponSpec(
    id: 'corvus_codex',
    name: '코르부스 전술서',
    grade: '전설',
    attack: 1210,
    crit: 11,
    speed: 9,
    description: '룬 지점을 설치하고 연쇄 폭발을 명령',
    pattern: WeaponPattern.runeMine,
    ownerId: 'vesta',
  ),
  WeaponSpec(
    id: 'verdigris_halberd',
    name: '녹청 파성극',
    grade: '전설',
    attack: 1540,
    crit: 8,
    speed: -2,
    description: '넓은 부채꼴을 쓸어 다수의 방어를 분쇄',
    pattern: WeaponPattern.halberdSweep,
    ownerId: 'rask',
  ),
  WeaponSpec(
    id: 'noctis_crescent',
    name: '녹티스 월륜검',
    grade: '전설',
    attack: 1330,
    crit: 17,
    speed: 11,
    description: '초승달 검기가 왕복하며 마법 피해를 줌',
    pattern: WeaponPattern.crescentWave,
    ownerId: 'iris',
  ),
  WeaponSpec(
    id: 'frost_standard',
    name: '백야 서리군기',
    grade: '영웅',
    attack: 980,
    crit: 7,
    speed: 3,
    description: '서리 토템을 세워 주변 적을 감속',
    pattern: WeaponPattern.frostTotem,
  ),
  WeaponSpec(
    id: 'spirit_lantern',
    name: '혼불 등롱',
    grade: '영웅',
    attack: 940,
    crit: 10,
    speed: 13,
    description: '혼령 사역마가 가까운 적을 자동 추적',
    pattern: WeaponPattern.spiritFamiliar,
  ),
  WeaponSpec(
    id: 'storm_feathers',
    name: '폭풍깃 투검',
    grade: '영웅',
    attack: 1010,
    crit: 15,
    speed: 16,
    description: '깃날이 적 사이를 빠르게 연쇄 도약',
    pattern: WeaponPattern.featherChain,
  ),
];
